/*
 * Bookstore
 *
 * A simple Bookstore API example.
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ListBooksResponse struct {

	Books []Book `json:"books"`
}
