/*
 * Bookstore
 *
 * A simple Bookstore API example.
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ListShelvesResponse struct {

	Shelves []Shelf `json:"shelves,omitempty"`
}
