/*
 * Bookstore
 *
 * A simple Bookstore API example.
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/vgb/bookstore/1.0/",
		Index,
	},

	Route{
		"CreateBook",
		strings.ToUpper("Post"),
		"/vgb/bookstore/1.0/shelves/{shelf}/books",
		CreateBook,
	},

	Route{
		"CreateShelf",
		strings.ToUpper("Post"),
		"/vgb/bookstore/1.0/shelves",
		CreateShelf,
	},

	Route{
		"DeleteBook",
		strings.ToUpper("Delete"),
		"/vgb/bookstore/1.0/shelves/{shelf}/books/{book}",
		DeleteBook,
	},

	Route{
		"DeleteShelf",
		strings.ToUpper("Delete"),
		"/vgb/bookstore/1.0/shelves/{shelf}",
		DeleteShelf,
	},

	Route{
		"DeleteShelves",
		strings.ToUpper("Delete"),
		"/vgb/bookstore/1.0/shelves",
		DeleteShelves,
	},

	Route{
		"GetBook",
		strings.ToUpper("Get"),
		"/vgb/bookstore/1.0/shelves/{shelf}/books/{book}",
		GetBook,
	},

	Route{
		"GetShelf",
		strings.ToUpper("Get"),
		"/vgb/bookstore/1.0/shelves/{shelf}",
		GetShelf,
	},

	Route{
		"ListBooks",
		strings.ToUpper("Get"),
		"/vgb/bookstore/1.0/shelves/{shelf}/books",
		ListBooks,
	},

	Route{
		"ListShelves",
		strings.ToUpper("Get"),
		"/vgb/bookstore/1.0/shelves",
		ListShelves,
	},
}
